#!/bin/sh

set -e
set -x

cd /tmp/django

apt-get update
apt-get -y --no-install-recommends install python3-pip
pip3 install . gunicorn
if [ -e requirements.txt ]; then
    pip3 install -r requirements.txt
fi
cp docker/init /init
chmod 0755 /init
apt-get clean
rm -rf /root/.cache
